baseURL = "/"
languageCode = "pl"
title = "Marek Tymowski"
theme = "ga3"
paginate = 3
DefaultContentLanguage = "pl"

disqusShortname = "tymowski-tk"
googleAnalytics = ""

[author]
  name = "Marek Tymowski"

[params]
   author = "Marek Tymowski"
   description = "Marek Tymowski - pisarz amator, włąsciciel agencji marketingowej, pozycjoner, webmaster."
   dateFormat = "2006-01-02"
   paginationSinglePost = true
   style = "light-without-switcher"
   readMore = true

[menu]

  [[menu.main]]
    identifier = "about"
    name = "O autorze"
    url = "/about/"
    weight = 3

  [[menu.main]]
    identifier = "categories "
    name = "Kategorie"
    url = "/categories/"
    weight = 2  
    title = "Kategorie"

  [[menu.main]]
    name = "Wpisy"
    identifier = "archive"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Kontakt"
    identifier = "contact"
    url = "/contact/"
    weight = 4  

[taxonomies]
category = "categories"
tag = "tags"

[markup.goldmark.renderer]
unsafe = true
