baseURL = "http://localhost"
languageCode = "pl"
title = "Marek Tymowski"
theme = "ga3"
paginate = 3
DefaultContentLanguage = "pl"

disqusShortname = ""
googleAnalytics = ""

[author]
  name = "Marek Tymowski"

[params]
   author = "Dariusz Dahm"
   description = "Marek Tymowski - pisarz amator, włąsciciel agencji marketingowej, pozycjoner, webmaster."
   dateFormat = "2006-01-02"
   paginationSinglePost = true
   style = "light-without-switcher"
   readMore = true

[menu]

  [[menu.main]]
    identifier = "about"
    name = "O autorze"
    url = "/about/"
    weight = 4

  [[menu.main]]
    identifier = "tags"
    name = "Tagi"
    url = "/tags/"
    weight = 2

  [[menu.main]]
    identifier = "categories"
    name = "Kategorie"
    url = "/categories/"
    weight = 3  

  [[menu.main]]
    name = "Wpisy"
    identifier = "archive"
    url = "/"
    weight = 1

[taxonomies]
category = "categories"
tag = "tags"

[markup.goldmark.renderer]
unsafe = true
