baseURL = ""
languageCode = "pl-pl"
title = "< Dahm />"
theme = "ga3"
paginate = 3
DefaultContentLanguage = "pl-pl"

disqusShortname = ""
googleAnalytics = ""

[author]
  name = "Dariusz Dahm"

[params]
   author = "Dariusz Dahm"
   description = "Anubis is a simple minimalist theme for Hugo blog engine."
   dateFormat = "2006-01-02"
   paginationSinglePost = true
   style = "light-without-switcher"
   readMore = false

[menu]

  [[menu.main]]
    identifier = "about"
    name = "O mnie"
    url = "/about/"
    weight = 1

  [[menu.main]]
    identifier = "tags"
    name = "Tagi"
    url = "/tags/"
    weight = 2

  [[menu.main]]
    name = "Archiwum"
    identifier = "archive"
    url = "/archive/"
    weight = 3

[taxonomies]
category = "categories"
tag = "tags"

[markup.goldmark.renderer]
unsafe = true
